import './globals.css'
import { PT_Serif } from 'next/font/google'

import Navbar from './components/navbar'

const pt_serif = PT_Serif({
  subsets: ["latin"],
  weight: ["400", "700"]
});

export const metadata = {
  title: 'YourPhotos',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={pt_serif.className}>
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  )
}
